# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
