# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_room_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Room')),
            ],
            options={
                'db_table': 'word',
                'verbose_name_plural': 'Words',
            },
        ),
    ]
