# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_wordbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_words',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterModelTable(
            name='wordbank',
            table='wordbank',
        ),
    ]
