# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20170120_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbank',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
